RULE_CONFIG_FILE = "rule_config_jsons/ruleConfigs.json"
COLLECTION_CONFIG_FILE = "rule_config_jsons/collections.json"

SUPPORTED_DL_FRAMEWORKS = {"TENSORFLOW", "MXNET", "PYTORCH"}
SUPPORTED_FRAMEWORKS = {"TENSORFLOW", "MXNET", "PYTORCH", "XGBOOST"}
SUPPORTED_RULE_GROUPS = {"SIMPLE", "ALL"}
